[env]
TERM = "xterm-256color"

[terminal]
shell.program = "/bin/zsh"

[window]
startup_mode = "Maximized"

[general]
import = ["~/.config/alacritty/themes/themes/everforest_dark.toml"]

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
size = 13.0
